from django.urls import path, include
from sale.views import *

urlpatterns = [
    path('get_sp/', get_sp, name='get_sp'),
    path('get_nam/', get_nam, name='get_sp'),
    path('get_quy/<int:nam>/', get_quy, name='get_sp'),
    path('buudien/', buudien, name='buudien'),
    path('dulich/', dulich, name='dulich'),
    path('all/', get_list_all, name='get_list_all'),
    path('all/<int:sanpham_id>/', filter1, name='filter1'),
    path('all/<int:sanpham_id>/nam/<int:nam_id>/', filter2, name='filter2'),
    path('all/<int:sanpham_id>/quy/<int:quy_id>/', filter3, name='filter3'),
    path('all/nam/<int:nam_id>/', filter4, name='filter4'),
    path('all/quy/<int:quy_id>/', filter5, name='filter5'),
    path('dulich/<int:sanpham_id>/', dulich_filter1, name='dulich_filter1'),
    path('dulich/<int:sanpham_id>/<int:year_id>/', dulich_filter2, name='dulich_filter2'),
    path('dulich/<int:sanpham_id>/<int:quarter_id>/', dulich_filter3, name='dulich_filter3'),
    path('dulich/<int:year_id>/', dulich_filter4, name='dulich_filter4'),
    path('dulich/<int:quarter_id>/', dulich_filter5, name='dulich_filter5'),
    path('buudien/<int:sanpham_id>/', buudien_filter1, name='buudien_filter1'),
    path('buudien/<int:sanpham_id>/<int:year_id>/', buudien_filter2, name='buudien_filter2'),
    path('buudien/<int:sanpham_id>/<int:quarter_id>/', buudien_filter3, name='buudien_filter3'),
    path('buudien/<int:year_id>/', buudien_filter4, name='buudien_filter4'),
    path('buudien/<int:quarter_id>/', buudien_filter5, name='buudien_filter5'),
    path('tp/dulich/<str:city_name>/', tp_dulich_filter, name='tp_dulich_filter'),
    path('tp/dulich/<str:city_name>/<int:sanpham_id>', tp_dulich_filter1, name='tp_dulich_filter1'),
    path('tp/dulich/<str:city_name>/<int:sanpham_id>/<int:year_id>', tp_dulich_filter2, name='tp_dulich_filter2'),
    path('tp/dulich/<str:city_name>/<int:sanpham_id>/<int:quarter_id>', tp_dulich_filter3, name='tp_dulich_filter3'),
    path('tp/dulich/<str:city_name>/<int:year_id>', tp_dulich_filter4, name='tp_dulich_filter4'),
    path('tp/dulich/<str:city_name>/<int:quarter_id>', tp_dulich_filter5, name='tp_dulich_filter5'),

    path('tp/buudien/<str:city_name>/', tp_buudien_filter, name='tp_buudien_filter'),
    path('tp/buudien/<str:city_name>/<int:sanpham_id>', tp_buudien_filter1, name='tp_buudien_filter1'),
    path('tp/buudien/<str:city_name>/<int:sanpham_id>/<int:year_id>', tp_buudien_filter2, name='tp_buudien_filter2'),
    path('tp/buudien/<str:city_name>/<int:sanpham_id>/<int:quarter_id>', tp_buudien_filter3, name='tp_buudien_filter3'),
    path('tp/buudien/<str:city_name>/<int:year_id>', tp_buudien_filter4, name='tp_buudien_filter4'),
    path('tp/buudien/<str:city_name>/<int:quarter_id>', tp_buudien_filter5, name='tp_buudien_filter5'),
]